### ISSUE TITLE
Now what..

### ISSUE THREAD

**Issue by hellachella** [hellachella/retro-sign#1]
Hi @thomasjbradley

I've made it do half of the things.. But I feel like it's not right.  I couldn't wrap my brain around how to select everything in the css? So I selected it IN the JQuery.  Markbot is not happy. I was happy thought because it did most of the things.

So I basically have a natural disaster level of overcoding.

I'm still stuck though. I don't really want to take it further before checking in.

M

**Comment by hellachella** [comment]
adding a ss.   <img width="678" alt="screen shot 2016-03-29 at 9 34 32 pm" src="https://cloud.githubusercontent.com/assets/10465921/14129206/0ebc4eea-f5f6-11e5-9f59-c6624b63a499.png">

**Comment by thomasjbradley** [comment]
Yeah, that's a whole heck of a lot of Javascript.
The only thing the JS needs to do is `toggleClass()`—the rest should be solved by CSS.

All those `nth-child` things should be in the CSS, something like this:

``` css
.engage path {
  transition: all .5s linear;
}

.engage path:nth-child(2) {
  transition-delay: .3s;
}
```

If the class was added directly to the SVG, then you can use child selectors:

``` css
.is-engaged .engage path {
  fill: #f60;
}
```
